version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python3 --version
      - run: export FREESURFER_HOME=`pwd`
      - run: pip3 install --user -r requirements.txt
      - run: env
      - run: ls -l
